# This is a basic workflow to help you get started with Actions

name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3   

    - name: 📩 Deploy to domain
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: greenvision.media
        username: gvm@greenvision.media
        password: ${{secrets.FTP_PASSWORD}}
        local-dir: ./.website/
        server-dir: app.greenvision.media/public_html/
        protocol: ftps
